language: ruby

rvm:
  - 1.8.7

before_install:
  - gem update --system 2.1.11
  - gem --version

script:
  - bundle exec rake db:schema:load;
  - bundle exec rake db:test:prepare;
  - bundle exec rake

before_script:
  - psql -c 'create database bettermeans_db_test;' -U postgres
